---
title: "Plotting ROC curves"
output: html_document
---

```{r}
library(tidyverse)
library(lubridate)
source('utils/r-utils.R')
theme_set(theme_bw() + theme(legend.title = element_blank()))

```

```{r}
roc_df <- read_tsv('https://raw.githubusercontent.com/greenelab/wiki-nationality-estimate/master/models/LSTM_roc_curves.tsv') %>% 
  rename('region' = category) %>% 
  recode_region() %>% 
  group_by(region) %>%
  mutate(Sensitivity = tpr, Specificity = 1-fpr, dSens = c(abs(diff(1-tpr)), 0)) %>% 
  ungroup()

auc_df <- roc_df %>% 
  group_by(region) %>% 
  # add_count() %>% 
  summarise(auc = sum((1 - fpr) * dSens),
            n = n()) %>% 
  arrange(desc(auc)) %>%
  mutate(auc_pct = 100 * auc,
         reg_auc = paste0(region, ', AUC = ', round(auc_pct, 1), '%'))

region_levels <- c('Celtic English', 'European', 'East Asian', 'Hispanic', 'South Asian', 'Muslim', 'Israel', 'African')

fig_3a <- roc_df %>% 
  left_join(auc_df, by = 'region') %>% 
  ggplot(aes(x = Sensitivity, y = Specificity, color = fct_relevel(reg_auc, as.character(auc_df$reg_auc)))) +
  scale_color_manual(values = c('#b3de69', '#fdb462', '#8dd3c7', '#fccde5', '#ffffb3', '#bebada',  '#80b1d3', '#fb8072')) +
  geom_step(size = 1, alpha = 0.8) +
  coord_fixed() +
  scale_x_reverse(breaks = seq(1, 0, -0.2), labels = scales::percent) +
  scale_y_continuous(breaks = seq(0, 1, 0.2), labels = scales::percent, limits = c(NA, 1.05)) +
  theme(legend.position = c(0.6, 0.4), 
        legend.text.align = 1)
```


```{r}
library(caret)

predictions_df <- read_tsv('https://raw.githubusercontent.com/arielah/wiki-nationality-estimate/predictions/data/LSTM_results_test.tsv') %>% 
  mutate(y_true = as.factor(truth)) %>% 
  select(-truth)

regs <- predictions_df %>% select(African:SouthAsian) %>% colnames()
cal_dfs <- list()
for (reg in regs) {
  pred_reg <- predictions_df %>%
    mutate(y_true_bin = as.factor((y_true == reg))) %>%
    rename(prob = reg) %>% 
    select(y_true_bin, prob)
  
  cal_dfs[[reg]] <- calibration(y_true_bin ~ prob,
                                data = pred_reg,
                                cuts = 20,
                                class = 'TRUE')$data %>%
    mutate(region = reg)
}
cal_dfs$EastAsian

```

```{r}
fig_3b <- bind_rows(cal_dfs) %>%
  recode_region() %>% 
  ggplot(aes(x = midpoint/100, y = Percent/100, color = fct_relevel(region, as.character(auc_df$region)))) +
  geom_abline(slope = 1, linetype = 2, alpha = 0.5) +
  scale_y_continuous(labels = scales::percent_format(accuracy = 20L), breaks = seq(0, 1, 0.2), limits = c(-0.005, 1.045)) +
  scale_x_continuous(labels = scales::percent_format(accuracy = 20L), breaks = seq(0, 1, 0.2), limits = c(0, 1)) +
  coord_fixed() +
  geom_point() +
  geom_line() +
  scale_color_manual(values = c('#b3de69', '#fdb462', '#8dd3c7', '#fccde5', '#ffffb3', '#bebada',  '#80b1d3', '#fb8072')) +
  theme(legend.position = 'None') +
  labs(x = 'Predicted probability', y = 'Fraction of names')

fig_3b
calibration_plot <- cowplot::plot_grid(fig_3a, fig_3b, labels = 'AUTO', nrow = 1, align = 'h')
ggsave('figs/fig_3.png', calibration_plot, height = 3.7, width = 7)

```

```{r}
library(superheat)
heat_dat <- predictions_df %>% 
  group_by(y_true) %>% 
  summarise_at(vars(African:SouthAsian), mean, na.rm = T) %>% 
  rename('region' = y_true,
         'Celtic English ' = 'CelticEnglish',
         'East Asian ' = 'EastAsian',
         'South Asian ' = 'SouthAsian',
         'African ' = 'African',
         'European ' = 'European',
         'Israel ' = 'Israel',
         'Hispanic ' = 'Hispanic',
         'Muslim ' = 'Muslim') %>% 
  # recode_region() %>%
  mutate(
    region = fct_recode(
      region, 
      'Celtic English ' = 'CelticEnglish',
         'East Asian ' = 'EastAsian',
         'South Asian ' = 'SouthAsian',
         'African ' = 'African',
         'European ' = 'European',
         'Israel ' = 'Israel',
         'Hispanic ' = 'Hispanic',
         'Muslim ' = 'Muslim')
  ) %>% 
column_to_rownames('region')
ordered_regs <- paste0(as.character(auc_df$region), ' ')


my_heat <- superheat(
  heat_dat[ordered_regs, ordered_regs],
  grid.hline.col = "white",
  grid.vline.col = "white",
  heat.pal = rev(viridis::inferno(3)),
  left.label.text.alignment = 'right',
  bottom.label.text.alignment = 'right',
  left.label.col = 'white',
  bottom.label.text.angle = 90,
  bottom.label.text.size = 4, 
  left.label.text.size = 4,
  bottom.label.col = 'white',
  padding = 0.5,
  row.title = 'True label',
  column.title = 'Prediction'
)

pdf('figs/heat_confusion.pdf')
superheat(
  heat_dat[ordered_regs, ordered_regs],
  grid.hline.col = "white",
  grid.vline.col = "white",
  heat.pal = rev(viridis::inferno(3)),
  left.label.text.alignment = 'right',
  bottom.label.text.alignment = 'right',
  left.label.col = 'white',
  bottom.label.text.angle = 90,
  bottom.label.text.size = 4, 
  left.label.text.size = 4,
  bottom.label.col = 'white',
  padding = 0.5,
  row.title = 'True label',
  column.title = 'Prediction'
)
dev.off()


```

```{r}
n_obs <- sum(auc_df$n)
heat_dat <- predictions_df %>% 
  rename('region' = y_true,
         'Celtic English' = 'CelticEnglish',
         'East Asian' = 'EastAsian',
         'South Asian' = 'SouthAsian') %>% 
  recode_region() %>% 
  group_by(region) %>% 
  summarise_at(vars(African:`South Asian`), mean, na.rm = T) %>% 
  ungroup() %>% 
  rename('reg_true' = region) %>% 
  pivot_longer(-reg_true, names_to = 'region', values_to = 'pred_prob') %>% 
  left_join(auc_df, by = 'region') %>% 
  mutate(scale_pred_prob = pred_prob/(n/n_obs))

ggplot(heat_dat, aes(reg_true, region, fill = log2(scale_pred_prob))) + 
  geom_tile() +
  scale_fill_gradient2(midpoint = 0, high = '#440154FF', low = '#94D840FF')

scales::show_col(viridis_pal(option = 'D')(20))
viridis_pal(option = 'D')(20)
```

