---
title: "Intersection analysis of race/ethnicity and gender"
output: html_document
---


```{r setup, include=FALSE}
library(tidyverse)
library(lubridate)
source('utils/r-utils.R')
library(wru)
theme_set(
  theme_bw() + 
    theme(panel.grid.minor = element_blank(),
          legend.title = element_blank()))

alpha_threshold <- qnorm(0.975)
start_year <- 1997
end_year <- 2019
n_years <- end_year - start_year

race_levels <- c('White', 'Asian', 'Black', 'Hispanic', 'Other', 'Other categories')
```


```{r}
all_full_names <- read_tsv('data/names/full-names.tsv.xz')
world <- rnaturalearth::ne_countries(scale='medium',returnclass = 'sf') 
nat_to_reg <- world %>% 
  as_tibble() %>% 
  select(iso_a2, name, region_wb) %>% 
  rename('countries' = iso_a2,
         'country_name' = name,
         'region' = region_wb)

# looking at only US affiliation
pubmed_aff_pmids <- read_tsv('data/names/corresponding-authors.tsv.xz') %>%
  left_join(read_tsv('data/pubmed/articles.tsv.xz'), by = 'pmid') %>%
  mutate(year = substr(publication_date, 1, 4) %>% ymd(truncated = 2),
         publication_date = ymd(publication_date, truncated = 2)) %>% 
  separate_rows(countries, sep = ',') %>% 
  filter(countries == 'US')
  
pubmed_race_pmids <- pubmed_aff_pmids %>%
  # rename('surname' = last_name) %>% 
  # left_join(all_full_names, by = c('fore_name', 'last_name')) %>% 
  rename('surname' = last_name_simple) %>% 
  predict_race(surname.only = T, impute.missing = F) 

pubmed_us_race <- pubmed_race_pmids %>% 
  # filter(!is.na(pred.whi)) %>% 
  group_by(pmid, journal, publication_date, year) %>% 
  summarise_at(vars(contains('pred.')), mean, na.rm = T) %>% 
  ungroup()

iscb_us_race <- read_tsv('data/iscb/keynotes.tsv') %>%
  mutate(publication_date = ymd(year, truncated = 2),
         year = ymd(year, truncated = 2)) %>% 
  separate_rows(afflcountries, sep = '\\|') %>% 
  filter(afflcountries == 'United States') %>% 
  # left_join(all_full_names, by = c('fore_name', 'last_name')) %>% 
  rename('surname' = last_name) %>% 
  # rename('surname' = last_name) %>%
  predict_race(surname.only = T, impute.missing = F)

my_jours <- unique(pubmed_us_race$journal)
my_confs <- unique(iscb_us_race$conference)
n_jours <- length(my_jours)
n_confs <- length(my_confs)
```

Missing data:
```{r}
iscb_us_race %>% filter(is.na(pred.whi)) %>% nrow()
iscb_us_race %>% filter(is.na(surname)) %>% nrow()
iscb_us_race %>% nrow()
# pubmed_us_race %>% filter(is.na(simple_last_name)) %>% nrow()
pubmed_race_pmids %>% filter(is.na(pred.whi)) %>% nrow()
```


```{r}
iscb_pubmed <- iscb_us_race %>%
  rename('journal' = conference) %>% 
  select(year, journal, contains('pred')) %>%
  mutate(publication_date = year,
         type = 'Keynote speakers/Fellows') %>%
  bind_rows(
    pubmed_us_race %>%
      select(year, journal, contains('pred'), publication_date) %>%
      mutate(type = 'Pubmed authors')
  ) %>%
  mutate(pred_sum_others = pred.his + pred.oth + pred.bla) %>% 
  pivot_longer(contains('pred'),
               names_to = 'Race',
               values_to = 'probabilities') %>%
  recode_race() %>%
  group_by(type, year, publication_date, Race) %>%
  add_count() %>%
  mutate(
    mean_prob = mean(probabilities, na.rm = T),
    sd_prob = sd(probabilities, na.rm = T),
    n = mean(n),
    me_prob = alpha_threshold * sd_prob / sqrt(n)
  ) %>%
  ungroup() 
```

```{r}
pubmed_race <- vector('list', length = n_jours)
i <- 0
for (jour in my_jours){
  i <- i + 1
  pubmed_race[[i]] <- iscb_pubmed %>%
    filter(type == 'Pubmed authors' & journal == jour & (Race != 'Other categories')) %>%
    group_by(year, Race, journal) %>%
    summarise(mean_prob = mean(probabilities, na.rm = T)) %>%
    ungroup()
}

iscb_race <- vector('list', length = n_confs)
i <- 0
for (conf in my_confs){
  i <- i + 1
  iscb_race[[i]] <- iscb_pubmed %>%
    filter(type != 'Pubmed authors' & journal == conf & (Race != 'Other categories')) %>%
    group_by(year, Race, journal) %>%
    summarise(mean_prob = mean(probabilities, na.rm = T)) %>%
    ungroup()
}
```


```{r fig.height=7}
fig_stats <- iscb_pubmed %>% 
  filter(Race %in% c('White', 'Asian', 'Other categories')) %>% 
  loess_and_ci() +
  theme(legend.position = c(0.84, 0.78)) +
  facet_wrap(vars(fct_rev(Race)))

fig_2a <- iscb_pubmed %>%
  filter(Race != 'Other categories',
         type == 'Pubmed authors') %>%
  group_by(year, type, Race) %>%
  summarise(mean_prob = mean(probabilities, na.rm = T)) %>%
  ungroup() %>%
  race_breakdown(category = 'main', type) 

fig_2c <- iscb_pubmed %>%
  filter(Race != 'Other categories',
         type != 'Pubmed authors') %>%
  group_by(year, type, Race) %>%
  summarise(mean_prob = mean(probabilities, na.rm = T)) %>%
  ungroup() %>%
  race_breakdown(category = 'main', type)

fig_2b <- bind_rows(pubmed_race) %>%
  race_breakdown(category = 'sub', journal) +
  theme(legend.position = c(0.8, 0.25),
        legend.key.height = unit(4, 'mm'),
        legend.background = element_rect(fill = "transparent", colour = "transparent"))

fig_2d <- bind_rows(iscb_race) %>%
  race_breakdown(category = 'sub', journal)

fig_2_a_d <- cowplot::plot_grid(fig_2a, fig_2b, fig_2c, fig_2d, labels = 'AUTO')
fig_2 <- cowplot::plot_grid(fig_2_a_d, fig_stats, labels = c('', 'E'), ncol = 1, rel_heights = c(2.2,1))
fig_2

ggsave('figs/us_racial_makeup.png', fig_2, width = 7, height = 7)
```
